version: "3.8"

services:
  inventory-postgres:
    image: postgres:16
    container_name: inventory-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: inventory
      POSTGRES_USER: inventory_user
      POSTGRES_PASSWORD: inventory_pass
    volumes:
      - inventory_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U inventory_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  inventory-adminer:
    image: adminer
    container_name: inventory-adminer
    ports:
      - "8086:8080"
    depends_on:
      - inventory-postgres

volumes:
  inventory_pg_data:
